# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: maven:3-openjdk-15-slim
    env:
      MAVEN_OPTS: "-javaagent:/tmp/contrast.jar -Dcontrast.api.token=${{ secrets.TOKEN }} -Dcontrast.application.name=Webgoat -Dcontrast.server.environment=DEVELOPMENT  -Dcontrast.server.name=GitHub -Dcontrast.application.version=$env:GITHUB_SHA"
      CONTRAST__APPLICATION__SESSION_METADATA: "committer=GitHub,branchName=$env:GITHUB_WORKFLOW_REF,version=$env:GITHUB_SHA,repository=Webgoat"


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.2.2
        with:
          # Repository name with owner. For example, actions/checkout
          repository: 'WebGoat/WebGoat'
          # The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch.
          ref: 'v8.2.2'


      # Runs a set of commands using the runners shell
      - name: Install agent
        run: |
          curl 'https://download.java.contrastsecurity.com/latest' -Lo /tmp/contrast.jar
          java -jar /tmp/contrast.jar
          ls  -l 

      # Runs a single command using the runners shell
      - name: Run tests
        run: mvn -Dtest="org/owasp/webgoat/*"  -Dmaven.test.failure.ignore=true -DfailIfNoTests=false clean install
