# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: maven:3-openjdk-15-slim

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.2.2
        with:
          # Repository name with owner. For example, actions/checkout
          repository: 'WebGoat/WebGoat'
          # The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch.
      
          ref: 'v8.2.2'
          # Personal access token (PAT) used to fetch the repository. The PAT is configured with the local git config, which enables your scripts to run authenticated git commands. The post-job step removes the PAT.


      # Runs a set of commands using the runners shell
      - name: Install agent
        run: |
          curl 'https://download.java.contrastsecurity.com/latest' -Lo /tmp/contrast.jar
          java -jar /tmp/contrast.jar

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
